name: test
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1


environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_neat_and_clean_calendar: ^0.3.0+12
  firebase_storage: ^11.2.8
  firebase_core: ^2.17.0
  table_calendar: ^3.0.9
  cloud_firestore: ^4.12.0

  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  firebase_messaging: ^14.6.9
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_foreground_task: ^6.1.2
  auto_route: ^7.8.4
  fluttertoast: ^8.2.2
  awesome_dialog: ^3.1.0
  google_sign_in_web: ^0.12.0+5
  image_picker: ^1.0.4
  firebase_database: ^10.3.2

  
  cupertino_icons: ^1.0.2
  firebase_core_dart: ^1.0.1
  provider:



  workmanager: ^0.5.2
  font_awesome_flutter: ^10.5.0
  image_cropper: ^5.0.0
  path_provider: ^2.1.1
  flutter_image_compress: ^2.0.4
  flutter_riverpod: ^2.3.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


  
  
  #cupertino_icons: ^1.0.2
  
  #image_picker: ^1.0.4
  get: any
  #http: any
  #intl:
  date_picker_timeline:
  flutter_local_notifications:
  flutter_native_timezone:
  sqflite:
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0


    
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  
  assets:
     - assets/dog.jpeg
     - assets/cat.jpeg
     - assets/duck.jpeg
     - assets/hamster.jpeg
     - assets/mimi.jpeg
     - assets/kiko.jpeg
     - assets/jana.jpeg
     - assets/joj.jpeg
     - assets/joudy.jpeg
     - assets/lily.jpeg
     - assets/loji.jpeg
     - assets/lola.jpeg
     - assets/nour.jpeg
     - assets/po.jpeg
     - assets/pup.jpeg
     - assets/toti.jpeg
     - assets/bos.jpeg
     - assets/siamese.jpeg
     - assets/bangal.jpeg
     - assets/calico.jpeg
     - assets/hima.jpeg
     - assets/persian.jpeg
     - assets/ragdoll.jpeg
     - assets/scoot.jpeg
     - assets/tabby.jpeg
     - assets/blue.jpeg
     - assets/lab.jpeg
     - assets/german.jpeg
     - assets/french.jpeg
     - assets/bird.jpg
     - assets/fish.jpg
     - assets/lizerd.jpg
     - assets/monkey.jpg
     - assets/owl.jpg
     - assets/turtle.jpg
     - assets/mimi2.jpg
     - assets/angel.jpeg
     - assets/barn.jpeg
     - assets/betta.jpeg
     - assets/capu.jpeg
     - assets/cham.jpeg
     - assets/china.jpeg
     - assets/chinaH.jpeg
     - assets/dwarf.jpeg
     - assets/finch.jpeg
     - assets/gold.jpeg
     - assets/iguana.jpeg
     - assets/lulu.jpeg
     - assets/neck.jpeg
     - assets/paint.jpeg
     - assets/parrotlet.jpeg
     - assets/red.jpeg
     - assets/scops.jpeg
     - assets/speck.jpeg
     - assets/squirrel.jpeg
     - assets/syrian.jpeg
     - assets/tamarin.jpeg
     - assets/tortois.jpeg
     - assets/game.jpg
     - assets/free.jpg


