// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZAfhbhRSkR0RC166s1Vdh3alR9-zNKkc',
    appId: '1:877282308511:web:ee62203972b2c2655bcdaa',
    messagingSenderId: '877282308511',
    projectId: 'pet-project-de9a5',
    authDomain: 'pet-project-de9a5.firebaseapp.com',
    storageBucket: 'pet-project-de9a5.appspot.com',
    measurementId: 'G-VCDY7ERKN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMBH9PXHX5mdg-eOa77Are10Eq-XfbJTs',
    appId: '1:877282308511:android:59d16eea219792c75bcdaa',
    messagingSenderId: '877282308511',
    projectId: 'pet-project-de9a5',
    storageBucket: 'pet-project-de9a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-7FPGipgDYVTMG0dp4u5UlaUWqLZnGs',
    appId: '1:877282308511:ios:2d536be44e2804ad5bcdaa',
    messagingSenderId: '877282308511',
    projectId: 'pet-project-de9a5',
    storageBucket: 'pet-project-de9a5.appspot.com',
    androidClientId: '877282308511-bl1tsikcnbhmrhph8bl69foehrormnuj.apps.googleusercontent.com',
    iosClientId: '877282308511-62dgg371d5pti6k6igd3fohs25m3dm7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP-7FPGipgDYVTMG0dp4u5UlaUWqLZnGs',
    appId: '1:877282308511:ios:95d5edbfc731a5455bcdaa',
    messagingSenderId: '877282308511',
    projectId: 'pet-project-de9a5',
    storageBucket: 'pet-project-de9a5.appspot.com',
    androidClientId: '877282308511-bl1tsikcnbhmrhph8bl69foehrormnuj.apps.googleusercontent.com',
    iosClientId: '877282308511-8iibpems96p384aeagfmeh8emnqq0m57.apps.googleusercontent.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
